language: python
python:
- '3.4'
- '3.3'
- '2.7'
- '2.6'
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- deps='pip numpy scipy gdal'
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
- source activate test-environment
- pip install pyproj unittest2 wheel
- python setup.py install
script:
- python test/test_cli.py
- python test/test_functions.py
deploy:
  provider: pypi
  user: ariki
  password:
    secure: OVxkOvhQGUe029V9VM2ztGHAiH9IP282YChkn+aptwpdP87II5ONV+Qn3oxV0PaTCXCq6QnsaS5h7skxqKze+gwEUkoAmAoJk1NCP2GBXfEmYru8mnTiM9VA7OA4/3fPWwu8tb/WFFshEXPyggvIVoFr57iwCF4ujHOBy7BfoCs=
  on:
    repo: Ariki/guessproj
    branch: master
    python: '2.6'
  distributions: 'sdist bdist_wheel'
