language: python
sudo: false
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
    - python-gdal
    - proj-bin
    - libproj-dev
    - python-pyproj
python:
- '3.6'
- '3.3'
- '2.7'
- '2.6'
before_install:
- pip install -U pip
- pip install wheel
- export GDALVERSION=`gdalinfo --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'`
install:
- pip install unittest2 wheel numpy scipy "gdal>=$GDALVERSION"
- python setup.py install
script:
- python test/test_cli.py
- python test/test_functions.py
deploy:
  provider: pypi
  user: ariki
  password:
    secure: OVxkOvhQGUe029V9VM2ztGHAiH9IP282YChkn+aptwpdP87II5ONV+Qn3oxV0PaTCXCq6QnsaS5h7skxqKze+gwEUkoAmAoJk1NCP2GBXfEmYru8mnTiM9VA7OA4/3fPWwu8tb/WFFshEXPyggvIVoFr57iwCF4ujHOBy7BfoCs=
  on:
    repo: Ariki/guessproj
    branch: master
    python: '2.6'
  distributions: 'sdist bdist_wheel'
